name: share_widgets
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.0
  chewie: ^1.3.1
  design:
    path: ../design
  flutter:
    sdk: flutter
  image_picker: ^0.8.5
  keyboard_actions: ^3.4.7
  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/delete.png
    - assets/zwwl.png
    - assets/none.png
    - assets/search.png
    - assets/ic_arrow_right.png
    - assets/ic_back_black.png
